=== RaiNigam/webLabReportXML/11.phone.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmIns:xs="http://www.w3.org/2001/XMLSchema" >
<xs:element name="phoneNumbers">
<xs:complexType>
<xs:sequence>
<xs:element name="entries">
<xs:element name="title" type="xs:string" maxOccurs="unbounded"></xs:element>
<xs:complexType>
<xs:sequence>
<xs:element name="entry" minOccurs="0" maxOccurs="unbounded"> <xs:complexType>
<xs:sequence>
<xs:element name="name"> <xs:complexType>
<xs:sequence>
<xs:element name="first" type="xs:string" ></xs:element> <xs:element name="middle" type="xs:string" minOccurs="0"
maxOccurs="1"></xs:element>
<sielement name="last" type="xs:string"></xs:element>
</xs:sequence>
<xs:attribute name="gender" type="xs:string"></xs:attribute>
</xs:complexType>
</xs:element>
<xs:element name="phone" type="xs:string"></xs:element> <xs:element name="city" type="xs:string" minOccurs="0" maxOccurs="1"></xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== RaiNigam/webLabReportXML/12.xml
<?xml version="1.0" encoding="UTF-8"?>
<phoneNumbers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="11.phone.xsd">
<title>Test</title>
<entries>
<entry>
<name gender="male">
<first>test</first>
<middle>dsfds</middle>
<last>sdfdsf</last>
</name>
<phone>987545454</phone>
<city>Chitwan,Kathmandu</city>
</entry>
<entry>
<name gender="female">
<first>test</first>
<middle>dsfds</middle>
<last>sdfdst</last>
</name>
<phone>987545454</phone>
</entry>
</entries>
</phoneNumbers>
