=== RaiNigam/webLabReportXML/12.restriction.xsd
<?xml version="1.0"?>
<xs:schema xmIns:xs="http://www.w3.org/2001/XMLSchema">
<xs:simpleType name="cityType">,
<xs:restriction base="xs:string">
<xs:enumeration value="Kathmandu"/> <xs:enumeration value="Pokhara" /> <xs:enumeration value="Chitwan"/> <xs:enumeration value="Butwal"/> <xs:enumeration value="Biratnagar" />
</xs:restriction>
</xs:simpleType>
<xs:complexType name="nameType">
<xs:sequence>
<xs:element name="first" type="xs:string"/> <xs:element name="middle" type="xs:string" minOccurs="0">
<xs:element name="last" type="xs:string" />
</xs:sequence>
<xs:attribute name="gender">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:pattern value="male | female"/>
</xs:restriction>
</xs:simpleType>
</xs:attribute>
</xs:complexType>
<xs:simpleType name="phoneType">
<xs:restriction base="xs:string">
<xs:pattern value="\d{3}-\d{4)"/>
</xs:restriction>
</xs:simpleType>
<xs:complexType name="entryType">
<xs:sequence>
<xs:element name="name" type="nameType" /> <xs:element name="phone">
<xs:complexType>
<xs:simpleContent>
<xs:extension base="phoneType">
<xs:attribute name="areaCode">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:pattern
value="\d{3)" />
</xs:restriction>
</xs:simpleType>
</xs:attribute>
</xs:extension>
</xs:simpleContent>
</xs:complexType>
</xs:element>
<xs:element name="city" type="cityType" minOccurs="0" />
</xs:sequence>
</xs:complexType>
<xs:element name="phoneNumbers">
<xs:complexType>
<xs:sequence>
<xs:element name="title" type="xs:string" /> <xs:element name="entries">
<xs:complexType>
<xs:sequence>
<xs:element name="entry" type="entryType"
minOccurs="0" maxOccurs="unbounded"/>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== RaiNigam/webLabReportXML/13.xml
<?xml version="1.0" standalone="no" ?>
<phoneNumbers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="12.restriction.xsd">
<title>Phone Numbers</title>
<entries>
<entry>
<name>
<first>Ram</first> <last>Thapa</last>
</name>
<phone areaCode="319">335-0055</phone>
<city>Pokhara</city>
</entry>
<entry>
<name gender="male">
<first>Hari</first> <last>Sharma</last>
</name>
<phone>354-9876</phone>
<city>Kathmandu</city>
</entry> <entry>
<name gender="female">
<first>Ramesh</first>
<middle>Prasad</middle>
<last>Shah</last>
</name>
<phone areaCode="319">335-4582</phone>
<city>Chitwan</city>
</entry> <entry>
<name gender="female">
<first>Ritu</first>
<last>Shrestha</last>
</name>
<phone>337-5967</phone>
</entry>
</entries>
</phoneNumbers>
