=== RaiNigam/webLabReportXML/5.notes.dtd
<!ELEMENT notes (note+)>
<!ELEMENT note (to, from, subject, message)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT subject (#PCDATA)>
<!ELEMENT message (#PCDATA)>

=== RaiNigam/webLabReportXML/6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE notes SYSTEM "5.notes.dtd"> 
<notes>
<note>
<to>Ramesh</to>
<from>Krishna</from>
<subject> This is my first xml</subject>
<message>This is my first message for xml</message>
</note>
<note>
<to>Sita</to>
<from>Gita</from>
<subject> This is my first xml</subject>
<message> This is my second message for xml</message> </note>
</notes>
